name: Invoke Worker

on:
  pull_request:
  push:

jobs:
  invoke_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run worker.js
        run: node action-worker.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}