name: Invoke Worker

on:
  pull_request:
  push:

jobs:
  invoke_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run worker.js
        run: node action-worker.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}